config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'}
  root 'items#index'
  get 'items/search'
  post 'items/search'
  get 'reviews/list'
  post 'reviews/list'
  get 'users/favorite'
  get 'users/review'
  resources :users
  resources :items, only: [:index, :create, :show, :destroy]
  resources :reviews, only: [:new, :create, :show, :destroy]
  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable

  has_many :items, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments,  dependent: :destroy

  mount_uploader :avatar, AvatarUploader
  validates :nickname, presence: true

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :move_to_root

  def favorite
    @user = User.find(params[:id])
    @items = @user.items.order("created_at DESC").page(params[:page]).per(5)
    @reviews = @user.reviews.order("created_at DESC").page(params[:page]).per(5)
  end

  def review
    @user = User.find(params[:id])
    @items = @user.items.order("created_at DESC").page(params[:page]).per(5)
    @reviews = @user.reviews.order("created_at DESC").page(params[:page]).per(5)
  end

  def show
    @user = User.find(params[:id])
    @items = @user.items.order("created_at DESC").page(params[:page]).per(5)
    @reviews = @user.reviews.order("created_at DESC").page(params[:page]).per(5)
  end


  private

  def move_to_root
    @user = User.find(params[:id])
    redirect_to root_path unless user_signed_in? && current_user.id == @user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_header.html.haml
.header
  .header__container
    .header__topbox
      .header__topbox__title
        =link_to "OTORIYOSE", root_path
      .header__topbox__input
        = form_with url: items_search_path, method: :get, local: true do |f| 
          = f.text_field :keyword, placeholder: "キーワードから探す", class: "form-control"
          = f.submit "検索", class: "btn btn-primary"
    .header__lowerbox
      .header__lowerbox__nickname
        = "NICKNAME : #{@user.nickname}"
      .header__lowerbox__logbox
        - if user_signed_in?
          = link_to "マイページ", user_path(current_user.id),class: "header__lowerbox__logbox__1"
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header__lowerbox__logbox__2"
        - else
          = link_to 'ログイン', new_user_session_path, class: "header__lowerbox__logbox__1"
          = link_to '新規登録', new_user_registration_path, class: "header__lowerbox__logbox__2"

app/views/users/favorite.html.haml
= render "header"

.search-view
  .search-view__title
    %h1 お気に入り一覧
  - if @items.present? 
    - @items.each do |item|
      - search_item = RakutenWebService::Ichiba::Item.search(itemCode: item.itemcode).first
      .item-box
        %table.table-hover
          %td.item-box__item-image
            = link_to (image_tag(search_item['mediumImageUrls'][0])), search_item['itemUrl'], target: :_blank
          %td.item-box__item-name
            = link_to search_item['itemName'], search_item['itemUrl'], target: :_blank
            %br
            %br
            - if user_signed_in?
              = form_with url: new_review_path, method: :get, local: true do |f|
                = f.hidden_field :itemcode, value: search_item['itemCode']
                = f.submit 'レビューを書く', class: "btn btn-primary btn-lg"
              = link_to "お気に入り削除", "/items/#{item.id}", method: :delete, class: "btn btn-danger btn-lg"
          %td.item-box__item-price
            = "￥#{search_item['itemPrice']}円"
  - else
    .item-box2
      %p お気に入りにした商品がありません

app/views/users/review.html.haml
= render "header"

.app-main
  .app-main__content
    .app-main__content__title
      %h1 レビュー一覧
    .app-main__content__review
      .app-main__content__review__box
        - if @reviews.present? 
          - @reviews.each do |review|
            - search_review = RakutenWebService::Ichiba::Item.search(itemCode: review.itemcode).first
            .review-container__box__content
              .review-container__box__content__box1
                .item-image
                  = link_to (image_tag(search_review['mediumImageUrls'][0])), search_review['itemUrl'], target: :_blank
                .item-title
                  = link_to search_review['itemName'], search_review['itemUrl'], target: :_blank
                .item-price
                  %p 商品価格
                  = "¥#{search_review['itemPrice']}円"
                .review-container__box__content__box1--new_review
                  .review-container__box__destroy
                    = link_to "レビュー詳細", review_path(review.id), class: "btn btn-primary btn-lg"
                    - if user_signed_in? && current_user.id == review.user.id
                      = link_to "レビュー削除", "/reviews/#{review.id}", method: :delete, class: "btn btn-danger btn-lg"
              .review-container__box__content__box2
                .review-container__box__content__box2__avater
                  .avater
                    - if review.user.avatar.blank?
                      = image_tag "member_photo_noimage_thumb.png", width: "100px", height: "100px"
                    - else
                      = image_tag review.user.avatar.to_s, width: "100px", height: "100px"
                  .reviewer
                    = "#{review.user.nickname}さん"
                .review-container__box__content__box2__title
                  %p タイトル
                  = review.title
                .review-container__box__content__box2__star
                  %p おいしさ
                  %div{id: "star-delicious#{review.id}"}
                  %p 手軽さ
                  %div{id: "star-eazy#{review.id}"}
                  %p コストパフォーマンス
                  %div{id: "star-cost#{review.id}"}

                  :javascript
                    $(document).on('turbolinks:load', function(){
                      $('#star-delicious#{review.id}').raty({
                        size: 36,
                        starOff: "#{asset_path('star-off.png')}",
                        starOn: "#{asset_path('star-on.png')}",
                        starHalf: "#{asset_path('star-half.png')}",
                        half: true,
                        readOnly: true,
                        score: "#{review.delicious}"
                      });

                      $('#star-eazy#{review.id}').raty({
                        size: 36,
                        starOff: "#{asset_path('star-off.png')}",
                        starOn: "#{asset_path('star-on.png')}",
                        starHalf: "#{asset_path('star-half.png')}",
                        half: true,
                        readOnly: true,
                        score: "#{review.eazy}"
                      });

                      $('#star-cost#{review.id}').raty({
                        size: 36,
                        starOff: "#{asset_path('star-off.png')}",
                        starOn: "#{asset_path('star-on.png')}",
                        starHalf: "#{asset_path('star-half.png')}",
                        half: true,
                        readOnly: true,
                        score: "#{review.cost}"
                      });
                    });
                
                .review-conteiner__box__content__box2__average
                  = "総合評価 : #{((review.delicious + review.eazy + review.cost) / 3).round(1)}点"
                  
          = paginate(@reviews)
        - else
          .review-container__box__content2
            %h3 レビューした商品がありません

app/views/users/show.html.haml
= render "header"

.mypage
  %h2.mypage__header= "マイページ"
  .mypage__container
    .mypage__container__content1
      %h3.title 商品
      %ul.mypage-lists 
        %li.mypage-list
          = form_with url: "/users/favorite", method: :get, local: true do |f|
            = f.hidden_field :id, value: current_user.id
            = f.submit 'お気に入り一覧', class: "btn btn-primary btn-lg"
        %li.mypage-list
          = form_with url: "/users/review", method: :get, local: true do |f|
            = f.hidden_field :id, value: current_user.id
            = f.submit 'レビュー一覧', class: "btn btn-primary btn-lg"
    .mypage__container__content2
      %h3.title 設定
      %ul.mypage-lists 
        %li.mypage-list
          = link_to '登録情報変更', edit_user_registration_path, class: 'btn btn-primary btn-lg'
        