config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'}
  root 'items#index'
  get 'items/search'
  post 'items/search'
  get 'reviews/list'
  post 'reviews/list'
  get 'users/favorite'
  get 'users/review'
  resources :users
  resources :items, only: [:index, :create, :show, :destroy]
  resources :reviews, only: [:new, :create, :show, :destroy]
  
  
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy

  validates :itemcode, :user_id, presence: true

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :destroy]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @saveditems = Item.all
    @items = Item.includes(:user).order("created_at DESC").page(params[:page]).per(5)
    @reviews = Review.includes(:user).order("created_at DESC").page(params[:page]).per(5)
  end

  def create
    @item = Item.find_or_create_by(item_params)
    redirect_back(fallback_location: items_search_path)
  end

  def show
    @search_item = RakutenWebService::Ichiba::Item.search(itemCode: @item.itemcode).first
    @reviews = Review.includes(:user).where(itemcode: @item.itemcode)
  end

  def search
    if params[:keyword].present?
      @items = RakutenWebService::Ichiba::Item.search(keyword: params[:keyword], genreId: 100227 )
    end
    @saveditems = Item.all
  end

  def destroy
    @item.delete
    redirect_back(fallback_location: users_favorite_path)
  end

  private

  def item_params
    params.permit(:itemcode).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/helpers/item_helper.rb
module ItemHelper
end

app/views/items/index.html.haml
.app-header
  .app-header__topbox
    .app-header__topbox__title
      %h1 OTORIYOSE
    .app-header__topbox__logbox
      - if user_signed_in?
        = link_to "マイページ", user_path(current_user.id),class: "app-header__topbox__logbox__1"
        = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "app-header__topbox__logbox__2"
      - else
        = link_to 'ログイン', new_user_session_path, class: "app-header__topbox__logbox__1"
        = link_to '新規登録', new_user_registration_path, class: "app-header__topbox__logbox__2"
  .app-header__middle
    %h2 OTORIYOSEとは？
    %p ◎お取り寄せ商品のレビューサイトです。
    %p ◎検索機能、レビューからお取り寄せ商品を検索できます。
    %P 
      ◎レビューでは、おいしさ、手軽さ、コストパフォーマンス
      %br 　の３点でお取り寄せ商品を評価できます。
  .app-header__lowerbox
    .app-header__lowerbox__content
      %h3 キーワードでお取り寄せ
    .app-header__lowerbox__input
      = form_with url: items_search_path, method: :get, local: true do |f| 
        = f.text_field :keyword, placeholder: "キーワードから探す", class: "form-control"
        = f.submit "検索", class: "btn btn-primary"
.app-main
  .app-main__content
    .app-main__content__title
      %h1 エリアから探す
    .app-main__content__area
      %label.app-main__content__area__box
        = image_tag 'top_img_tokyo.jpg', width: '125px', height: '125px', class: "img-thumbnail"
        = form_with url: items_search_path, method: :get, local: true do |f|
          = f.hidden_field :keyword, value: "東京 お取り寄せ"
          = f.submit '東京', class: "app-main__content__area__box__submit"
      %label.app-main__content__area__box
        = image_tag 'top_img_osaka.jpg', width: '125px', height: '125px', class: "img-thumbnail"
        = form_with url: items_search_path, method: :get, local: true do |f|
          = f.hidden_field :keyword, value: "大阪 お取り寄せ"
          = f.submit '大阪', class: "app-main__content__area__box__submit"
      %label.app-main__content__area__box
        = image_tag 'top_img_hokkaido.jpg', width: '125px', height: '125px', class: "img-thumbnail"
        = form_with url: items_search_path, method: :get, local: true do |f|
          = f.hidden_field :keyword, value: "北海道 お取り寄せ"
          = f.submit '北海道', class: "app-main__content__area__box__submit"
      %label.app-main__content__area__box
        = image_tag 'top_img_okinawa.jpg', width: '125px', height: '125px', class: "img-thumbnail"
        = form_with url: items_search_path, method: :get, local: true do |f|
          = f.hidden_field :keyword, value: "沖縄 お取り寄せ"
          = f.submit '沖縄', class: "app-main__content__area__box__submit"

    .app-main__content__title
      %h1 食材から探す
    .app-main__content__area
      %label.app-main__content__area__box
        = image_tag 'top_img_meet.jpg', width: '125px', height: '125px', class: "img-thumbnail"
        = form_with url: items_search_path, method: :get, local: true do |f|
          = f.hidden_field :keyword, value: "牛肉 お取り寄せ"
          = f.submit '牛肉', class: "app-main__content__area__box__submit"
      %label.app-main__content__area__box
        = image_tag 'top_img_susi.jpg', width: '125px', height: '125px', class: "img-thumbnail"
        = form_with url: items_search_path, method: :get, local: true do |f|
          = f.hidden_field :keyword, value: "寿司 お取り寄せ"
          = f.submit '寿司', class: "app-main__content__area__box__submit"
      %label.app-main__content__area__box
        = image_tag 'top_img_kaisen.jpg', width: '125px', height: '125px', class: "img-thumbnail"
        = form_with url: items_search_path, method: :get, local: true do |f|
          = f.hidden_field :keyword, value: "海鮮 お取り寄せ"
          = f.submit '海鮮', class: "app-main__content__area__box__submit"
      %label.app-main__content__area__box
        = image_tag 'top_img_cake.jpg', width: '125px', height: '125px', class: "img-thumbnail"
        = form_with url: items_search_path, method: :get, local: true do |f|
          = f.hidden_field :keyword, value: "スイーツ お取り寄せ"
          = f.submit 'スイーツ', class: "app-main__content__area__box__submit"

    .app-main__content__title
      %h1 レビューから探す
    .app-main__content__review
      .app-main__content__review__box
        - @reviews.each do |review|
          - search_review = RakutenWebService::Ichiba::Item.search(itemCode: review.itemcode).first
          .review-container__box__content
            .review-container__box__content__box1
              .item-image
                = link_to (image_tag(search_review['mediumImageUrls'][0])), search_review['itemUrl'], target: :_blank
              .item-title
                = link_to search_review['itemName'], search_review['itemUrl'], target: :_blank
              .item-price
                %p 商品価格
                = "¥#{search_review['itemPrice']}円"
              .review-container__box__content__box1--new_review
                = link_to 'レビュー詳細', review_path(review.id), class: "btn btn-primary btn-lg"
                - if user_signed_in?
                  - if @saveditems.where(user_id: current_user.id, itemcode: search_review['itemCode']).blank?
                    = form_with url: items_path, method: :post, local:true do |f|
                      = f.hidden_field :itemcode, value: search_review['itemCode']
                      = f.submit 'お気に入り登録', class: 'btn btn-primary btn-lg'
                  - else
                    = form_with url: new_review_path, method: :get, local: true do |f|
                      = f.hidden_field :itemcode, value: search_review['itemCode']
                      = f.submit 'レビューを書く', class: "btn btn-primary btn-lg"
            .review-container__box__content__box2
              .review-container__box__content__box2__avater
                .avater
                  - if review.user.avatar.blank?
                    = image_tag "member_photo_noimage_thumb.png", width: "100px", height: "100px"
                  - else
                    = image_tag review.user.avatar.to_s, width: "100px", height: "100px"
                .reviewer
                  = "#{review.user.nickname}さん"
              .review-container__box__content__box2__title
                %p タイトル
                = review.title
              .review-container__box__content__box2__star
                %p おいしさ
                %div{id: "star-delicious#{review.id}"}
                %p 手軽さ
                %div{id: "star-eazy#{review.id}"}
                %p コストパフォーマンス
                %div{id: "star-cost#{review.id}"}

                :javascript
                  $(document).on('turbolinks:load', function(){
                    $('#star-delicious#{review.id}').raty({
                      size: 36,
                      starOff: "#{asset_path('star-off.png')}",
                      starOn: "#{asset_path('star-on.png')}",
                      starHalf: "#{asset_path('star-half.png')}",
                      half: true,
                      readOnly: true,
                      score: "#{review.delicious}"
                    });

                    $('#star-eazy#{review.id}').raty({
                      size: 36,
                      starOff: "#{asset_path('star-off.png')}",
                      starOn: "#{asset_path('star-on.png')}",
                      starHalf: "#{asset_path('star-half.png')}",
                      half: true,
                      readOnly: true,
                      score: "#{review.eazy}"
                    });

                    $('#star-cost#{review.id}').raty({
                      size: 36,
                      starOff: "#{asset_path('star-off.png')}",
                      starOn: "#{asset_path('star-on.png')}",
                      starHalf: "#{asset_path('star-half.png')}",
                      half: true,
                      readOnly: true,
                      score: "#{review.cost}"
                    });
                  });
              
              .review-conteiner__box__content__box2__average
                = "総合評価 : #{((review.delicious + review.eazy + review.cost) / 3).round(1)}点"
                
      = paginate(@reviews)


    .app-main__content__title
      %h1 おすすめから探す
    .app-main__content__review
      .app-main__content__review__box
        -if user_signed_in?
          - @items.where.not(user_id: current_user.id).each do |item|
            - search_item = RakutenWebService::Ichiba::Item.search(itemCode: item.itemcode).first
            %table.table-hover
              %tr
                %td.td-item-image
                  = link_to (image_tag(search_item['mediumImageUrls'][0])), search_item['itemUrl'], target: :_blank
                %td.td-item-name
                  = search_item['itemName']
                  %br
                  %br
                  = link_to "商品詳細ページ", item_path(item.id), class: "btn btn-primary btn-lg"
                  - if @saveditems.where(user_id: current_user.id, itemcode: search_item['itemCode']).blank?
                    = form_with url: items_path, method: :post, local:true do |f|
                      = f.hidden_field :itemcode, value: search_item['itemCode']
                      = f.submit 'お気に入り登録', class: 'btn btn-primary btn-lg'
                %td.td-item-price
                  = "¥#{search_item['itemPrice']}円"
        - else
          - @items.each do |item|
            - search_item = RakutenWebService::Ichiba::Item.search(itemCode: item.itemcode).first
            %table.table-hover
              %tr
                %td.td-item-image
                  = link_to (image_tag(search_item['mediumImageUrls'][0])), search_item['itemUrl'], target: :_blank
                %td.td-item-name
                  = search_item['itemName']
                  %br
                  %br
                  = link_to "商品詳細ページ", item_path(item.id), class: "btn btn-primary btn-lg"
                %td.td-item-price
                  = "¥#{search_item['itemPrice']}円"
      = paginate(@items)

app/views/items/search.html.haml
= render "shared/header"

.search-view
  - if @items.present? 
    - @items.each do |item|
      .item-box
        %table.table-bordered
          %td.item-box__item-image
            = link_to (image_tag(item['mediumImageUrls'][0])), item['itemUrl'], target: :_blank
          %td.item-box__item-name
            = link_to item['itemName'], item['itemUrl'], target: :_blank
            %br
            %br
            - if user_signed_in?
              = form_with url: new_review_path, method: :get, local: true do |f|
                = f.hidden_field :itemcode, value: item['itemCode']
                = f.submit 'レビューを書く', class: "btn btn-primary btn-lg"
              - if @saveditems.where(user_id: current_user.id, itemcode: item['itemCode']).blank?
                = form_with url: items_path, method: :post, local:true do |f|
                  = f.hidden_field :itemcode, value: item['itemCode']
                  = f.submit 'お気に入り登録', class: 'btn btn-primary btn-lg'

          %td.item-box__item-price
            = "￥#{item['itemPrice']}円"
  - else
    .item-box
      .item-box__log
        %p キーワードが入力されていません
  

app/views/items/show.html.haml
= render "shared/header"
.item-new-main
  .item-new-main__container
    %table.table-bordered
      %tr
        %td.item-new-main__item-box__image
          = image_tag @search_item['mediumImageUrls'][0], class: "item-new-main__item-box__image__content"
        %td.item-new-main__item-box__name
          = @search_item['itemName']
          %br
          = link_to "商品購入ページ", @search_item['itemUrl'], target: :_blank
          - if user_signed_in? && current_user.id == @item.user.id
            = link_to "お気に入り削除", "/items/#{@item.id}", method: :delete
        %td.item-new-main__item-box__price
          = "¥#{@search_item['itemPrice']}円" 
    %table.table-bordered
      %tr
        %td 商品説明
      %tr
        %td.discription
          = @search_item['itemCaption']

    .review-container
      .review-container__box
        .review-container__box__title
          %p レビュー一覧
        - @reviews.each do |review|
          .review-container__box__content
            .review-container__box__content__container
              .review-container__box__content__container__box1
                .create-at
                  = review.created_at.to_date
                .avater-box
                  .avater
                    - if review.user.avatar.blank?
                      = image_tag "member_photo_noimage_thumb.png", width: "100px", height: "100px"
                    - else
                      = image_tag review.user.avatar.to_s, width: "100px", height: "100px"
                  .reviewer
                    = "#{review.user.nickname}"
                .review-conteiner__box__content__container__box1__average
                  = "総合評価 : #{((review.delicious + review.eazy + review.cost) / 3).round(1)}点"
                .review-container__box__content__container__box1__title
                  %p タイトル
                  = review.title
              .review-container__box__content__container__box2
                .review-container__box__content__container__box2__star
                  %p おいしさ
                  %div{id: "star-delicious#{review.id}"}
                  %p 手軽さ
                  %div{id: "star-eazy#{review.id}"}
                  %p コストパフォーマンス
                  %div{id: "star-cost#{review.id}"}

                  :javascript
                    $(document).on('turbolinks:load', function(){
                      $('#star-delicious#{review.id}').raty({
                        size: 36,
                        starOff: "#{asset_path('star-off.png')}",
                        starOn: "#{asset_path('star-on.png')}",
                        starHalf: "#{asset_path('star-half.png')}",
                        half: true,
                        readOnly: true,
                        score: "#{review.delicious}"
                      });

                      $('#star-eazy#{review.id}').raty({
                        size: 36,
                        starOff: "#{asset_path('star-off.png')}",
                        starOn: "#{asset_path('star-on.png')}",
                        starHalf: "#{asset_path('star-half.png')}",
                        half: true,
                        readOnly: true,
                        score: "#{review.eazy}"
                      });

                      $('#star-cost#{review.id}').raty({
                        size: 36,
                        starOff: "#{asset_path('star-off.png')}",
                        starOn: "#{asset_path('star-on.png')}",
                        starHalf: "#{asset_path('star-half.png')}",
                        half: true,
                        readOnly: true,
                        score: "#{review.cost}"
                      })
                    });

            .review-container__box__content__container2
              - if review.content.present?
                .review-container__box__content__container2__title
                  %p レビュー
                  = review.content
              .review-container__box__content__container2__image
                = image_tag "#{review.image}"


  = render 'shared/star'